var ALIASES = {};
ALIASES['chrono'] = {};
ALIASES['csa'] = {};
ALIASES['libc'] = {};
ALIASES['memchr'] = {};
ALIASES['nom'] = {};
ALIASES['num_integer'] = {};
ALIASES['num_traits'] = {};
ALIASES['time'] = {};
